import fs from "node:fs";
import path from "node:path";

/**
 * Turns the same-origin asset URLs in the generated stylesheet into data: URIs.
 *
 * The preview iframe can fetch `/fonts/inter/...` because it shares an origin
 * with the app. The PDF renderer cannot: it loads the document into Chromium
 * with `setContent`, which has no origin for a relative URL to resolve against,
 * so every font and every KaTeX glyph would silently fall back to a system face
 * and the PDF would not match the preview.
 *
 * Inlining also removes twenty-odd network round-trips from inside a serverless
 * function, which matters more than the byte count.
 */

const PUBLIC_DIR = path.join(process.cwd(), "public");

/**
 * Assets are immutable for the lifetime of a deployment, and a warm container
 * renders many documents. Reading Inter off disk once per process instead of
 * once per render is worth the few hundred KB.
 */
const cache = new Map<string, string>();

const MIME_TYPES: Record<string, string> = {
  ".woff2": "font/woff2",
  ".woff": "font/woff",
  ".ttf": "font/ttf",
  ".otf": "font/otf",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".svg": "image/svg+xml",
  ".webp": "image/webp",
};

export class AssetNotFoundError extends Error {
  constructor(url: string) {
    super(
      `Asset "${url}" is not in public/. Run \`npm run assets\` to regenerate ` +
        "the bundled fonts and stylesheets.",
    );
    this.name = "AssetNotFoundError";
  }
}

/**
 * Resolve a public URL to a file inside public/, refusing anything that escapes
 * it. The URLs handled here are all generated by our own code, but this is the
 * one place in the renderer where a string becomes a filesystem path, so it
 * checks anyway.
 */
function resolvePublicPath(url: string): string {
  const withoutQuery = url.split(/[?#]/)[0] ?? "";
  const decoded = decodeURIComponent(withoutQuery);
  const resolved = path.resolve(PUBLIC_DIR, `.${decoded}`);

  const relative = path.relative(PUBLIC_DIR, resolved);
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new AssetNotFoundError(url);
  }

  return resolved;
}

export function inlineAsset(url: string): string {
  const cached = cache.get(url);
  if (cached) return cached;

  const filePath = resolvePublicPath(url);
  if (!fs.existsSync(filePath)) throw new AssetNotFoundError(url);

  const mime = MIME_TYPES[path.extname(filePath).toLowerCase()];
  if (!mime) throw new AssetNotFoundError(url);

  const encoded = fs.readFileSync(filePath).toString("base64");
  const dataUri = `data:${mime};base64,${encoded}`;

  cache.set(url, dataUri);
  return dataUri;
}

/**
 * The `resolveUrl` implementation handed to the CSS generator.
 *
 * A missing asset degrades to the original URL rather than failing the render:
 * a document that comes out in a fallback font is far better than no document,
 * and the mismatch is obvious enough to notice.
 */
export function inlineAssetOrKeep(url: string): string {
  if (!url.startsWith("/")) return url;
  try {
    return inlineAsset(url);
  } catch {
    return url;
  }
}

/** Test seam. */
export function clearAssetCache(): void {
  cache.clear();
}
