import { load as loadYaml } from "js-yaml";
import rehypeHighlight from "rehype-highlight";
import rehypeKatex from "rehype-katex";
import rehypeRaw from "rehype-raw";
import rehypeSanitize from "rehype-sanitize";
import rehypeSlug from "rehype-slug";
import rehypeStringify from "rehype-stringify";
import remarkBreaks from "remark-breaks";
import remarkFrontmatter from "remark-frontmatter";
import remarkGemoji from "remark-gemoji";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import remarkParse from "remark-parse";
import remarkDirective from "remark-directive";
import remarkRehype from "remark-rehype";
import remarkSmartypants from "remark-smartypants";
import { unified } from "unified";
import { visit } from "unist-util-visit";
import { toString as mdastToString } from "mdast-util-to-string";
import { toString as hastToString } from "hast-util-to-string";
import type { BlockContent, Root as MdastRoot, RootContent } from "mdast";
// Type-only side-effect import: teaches mdast about containerDirective nodes,
// which remark-directive adds to the tree at runtime.
import type {} from "mdast-util-directive";
import type { Element, Root as HastRoot } from "hast";

import type { MarkdownConfig, StructureConfig } from "@/lib/config/schema";
import { buildSanitizeSchema } from "@/lib/renderer/sanitize";

/**
 * Markdown -> HTML.
 *
 * Pure and deterministic: no DOM, no network, no filesystem. That is what lets
 * the same function run in the browser for the live preview and on the server
 * for the PDF, and is the only reason the two can be guaranteed to match.
 *
 * The plugin order matters more than it looks. Sanitisation runs immediately
 * after raw HTML is parsed and *before* KaTeX and syntax highlighting inject
 * their own markup - otherwise the allowlist would have to whitelist every
 * class those two emit, which is a much larger hole than it sounds.
 */

export type ExtractedHeading = {
  /** 1 for h1, 6 for h6. */
  depth: number;
  /** Plain text, without any auto-generated section number. */
  text: string;
  /** "2.1.3" when heading numbering is on, otherwise null. */
  number: string | null;
  /** Anchor id, as generated by rehype-slug. */
  id: string;
};

export type RenderedMarkdown = {
  html: string;
  headings: ExtractedHeading[];
  frontMatter: Record<string, unknown>;
  /** Front matter `title`, else the first h1, else null. */
  title: string | null;
  wordCount: number;
};

export type MarkdownRenderOptions = {
  markdown: MarkdownConfig;
  structure: StructureConfig;
};

// ---------------------------------------------------------------------------
// Front matter
// ---------------------------------------------------------------------------

/**
 * Pulls the YAML block out of the tree and into `store`.
 *
 * remark-frontmatter only *recognises* the block - without this it would be
 * silently dropped on the way to HTML and its metadata lost. In "render" mode
 * we keep it visible by turning it into a fenced code block instead.
 */
function remarkFrontMatter(store: { data: Record<string, unknown> }, mode: MarkdownConfig["frontMatter"]) {
  return () => (tree: MdastRoot) => {
    const kept: RootContent[] = [];

    for (const node of tree.children) {
      if (node.type !== "yaml") {
        kept.push(node);
        continue;
      }

      if (mode === "parse") {
        try {
          const parsed = loadYaml(node.value);
          if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
            store.data = parsed as Record<string, unknown>;
          }
        } catch {
          // Malformed YAML is the author's problem, not a reason to fail the
          // whole render. Drop it and carry on.
        }
      }

      if (mode === "render") {
        kept.push({ type: "code", lang: "yaml", value: node.value });
      }
    }

    tree.children = kept;
  };
}

// ---------------------------------------------------------------------------
// Callouts
// ---------------------------------------------------------------------------

const CALLOUT_TYPES = [
  "note",
  "tip",
  "important",
  "warning",
  "caution",
  "info",
  "success",
  "danger",
  "example",
  "quote",
] as const;

type CalloutType = (typeof CALLOUT_TYPES)[number];

function isCalloutType(value: string): value is CalloutType {
  return (CALLOUT_TYPES as readonly string[]).includes(value);
}

/**
 * The callout heading, as a real element rather than a CSS `content: attr(...)`
 * pseudo-element. Text drawn by CSS is not selectable or searchable once it is
 * in a PDF, and does not survive text extraction - which defeats the point of
 * generating a text PDF rather than an image of one.
 */
function calloutTitle(text: string): BlockContent {
  return {
    type: "paragraph",
    data: { hName: "div", hProperties: { className: ["callout-title"] } },
    children: [{ type: "text", value: text }],
  };
}

/**
 * Accepts the callout syntax people actually type.
 *
 * remark-directive implements the generic directives proposal, which only
 * recognises `:::tip` and `:::tip[Title]`. Every tool that popularised this
 * syntax - Docusaurus, MkDocs, Obsidian - writes `::: tip` or `:::tip Title`,
 * both of which silently fall through as a paragraph of literal colons.
 * Normalising here is far kinder than making the user learn the difference.
 *
 * Fenced code is tracked and skipped, so a `:::note` *inside* a code sample
 * stays exactly as written.
 */
export function normaliseDirectiveSyntax(source: string): string {
  const lines = source.split(/\r?\n/);
  let openFence: string | null = null;

  const normalised = lines.map((line) => {
    const fence = /^\s{0,3}(`{3,}|~{3,})/.exec(line);
    if (fence?.[1]) {
      const marker = fence[1][0] as string;
      if (openFence === null) openFence = marker;
      else if (openFence === marker) openFence = null;
      return line;
    }
    if (openFence !== null) return line;

    const match = /^(\s{0,3})(:{3,})[ \t]*([A-Za-z][\w-]*)[ \t]*(.*)$/.exec(line);
    if (!match) return line;

    const [, indent = "", colons = ":::", name = "", rest = ""] = match;
    const trimmed = rest.trim();

    // Already canonical: `:::tip[Title]` or `:::tip{#id}`.
    if (trimmed.startsWith("[") || trimmed.startsWith("{")) return line;

    return trimmed === ""
      ? `${indent}${colons}${name}`
      : `${indent}${colons}${name}[${trimmed}]`;
  });

  return normalised.join("\n");
}

/**
 * GitHub alert syntax: a blockquote whose first line is `[!NOTE]`.
 *
 *   > [!WARNING]
 *   > This will overwrite the file.
 *
 * Becomes `<div class="callout callout-warning">` with a title row, so it can
 * be styled as a real callout box rather than a quote.
 */
function remarkGithubAlerts() {
  return (tree: MdastRoot) => {
    visit(tree, "blockquote", (node) => {
      const [first] = node.children;
      if (!first || first.type !== "paragraph") return;

      const [firstChild] = first.children;
      if (!firstChild || firstChild.type !== "text") return;

      const match = /^\[!([A-Za-z]+)\]\s*\n?/.exec(firstChild.value);
      if (!match?.[1]) return;

      const kind = match[1].toLowerCase();
      if (!isCalloutType(kind)) return;

      // Strip the marker from the first text node; drop the node if that
      // leaves it empty, and the paragraph if that leaves it empty.
      firstChild.value = firstChild.value.slice(match[0].length);
      if (firstChild.value === "") first.children.shift();
      if (first.children.length === 0) node.children.shift();

      node.children.unshift(
        calloutTitle(kind.charAt(0).toUpperCase() + kind.slice(1)),
      );

      node.data = {
        ...node.data,
        hName: "div",
        hProperties: { className: ["callout", `callout-${kind}`] },
      };
    });
  };
}

/**
 * Container directive syntax, as used by MkDocs, Docusaurus and friends:
 *
 *   ::: warning Custom title
 *   Body text.
 *   :::
 */
function remarkDirectiveCallouts() {
  return (tree: MdastRoot) => {
    visit(tree, "containerDirective", (node) => {
      if (!isCalloutType(node.name)) return;

      const label = node.children.find(
        (child) =>
          child.type === "paragraph" &&
          (child.data as { directiveLabel?: boolean } | undefined)
            ?.directiveLabel,
      );

      const title = label
        ? mdastToString(label)
        : node.name.charAt(0).toUpperCase() + node.name.slice(1);

      if (label) {
        node.children = node.children.filter((child) => child !== label);
      }

      node.children.unshift(calloutTitle(title));

      node.data = {
        ...node.data,
        hName: "div",
        hProperties: { className: ["callout", `callout-${node.name}`] },
      };
    });
  };
}

/**
 * `<!-- pagebreak -->` (or `<!-- pagebreak -->` with any casing/spacing) forces
 * a page break. An HTML comment is the right carrier: every other Markdown
 * renderer ignores it, so a document with breaks still reads correctly
 * elsewhere.
 */
function remarkPageBreaks() {
  return (tree: MdastRoot) => {
    visit(tree, "html", (node) => {
      if (!/^<!--\s*(page-?break|newpage)\s*-->$/i.test(node.value.trim())) {
        return;
      }
      node.data = {
        ...node.data,
        hName: "div",
        hProperties: { className: ["page-break"] },
        hChildren: [],
      };
    });
  };
}

// ---------------------------------------------------------------------------
// Headings
// ---------------------------------------------------------------------------

const HEADING_TAGS = new Set(["h1", "h2", "h3", "h4", "h5", "h6"]);

/**
 * Collects every heading and, when enabled, prefixes it with a section number.
 *
 * Doing this on the tree rather than with CSS counters costs one pass but buys
 * a lot: the table of contents needs the same numbers, and CSS counters cannot
 * be read back out.
 */
function rehypeHeadings(
  store: { headings: ExtractedHeading[] },
  structure: StructureConfig,
) {
  return () => (tree: HastRoot) => {
    const counters = [0, 0, 0, 0, 0, 0];

    visit(tree, "element", (node: Element) => {
      if (!HEADING_TAGS.has(node.tagName)) return;

      const depth = Number(node.tagName.slice(1));
      const text = hastToString(node).trim();
      const id = typeof node.properties?.id === "string" ? node.properties.id : "";

      let number: string | null = null;
      const index = depth - structure.numberFrom;

      if (
        structure.numberHeadings &&
        index >= 0 &&
        index < structure.numberDepth
      ) {
        counters[index] = (counters[index] ?? 0) + 1;
        for (let deeper = index + 1; deeper < counters.length; deeper += 1) {
          counters[deeper] = 0;
        }
        number = counters.slice(0, index + 1).join(".");

        // The trailing space is a real text node, not CSS margin, so that
        // `string-set: content(text)` picks it up and a running head reads
        // "3.2 District variation" instead of "3.2District variation".
        node.children.unshift(
          {
            type: "element",
            tagName: "span",
            properties: { className: ["heading-number"] },
            children: [{ type: "text", value: number }],
          },
          { type: "text", value: " " },
        );
      }

      store.headings.push({ depth, text, number, id });
    });
  };
}

// ---------------------------------------------------------------------------
// The pipeline
// ---------------------------------------------------------------------------

function countWords(tree: MdastRoot): number {
  // Deliberately not mdastToString(tree): that concatenates every node with no
  // separator, so "# Title" followed by "One two" counts as "TitleOne two".
  let count = 0;

  visit(tree, (node) => {
    if (
      node.type !== "text" &&
      node.type !== "inlineCode" &&
      node.type !== "code"
    ) {
      return;
    }
    const words = node.value.trim().match(/\S+/g);
    if (words) count += words.length;
  });

  return count;
}

export function renderMarkdown(
  source: string,
  options: MarkdownRenderOptions,
): RenderedMarkdown {
  const { markdown, structure } = options;

  const frontMatterStore = { data: {} as Record<string, unknown> };
  const headingStore = { headings: [] as ExtractedHeading[] };
  let wordCount = 0;

  const processor = unified().use(remarkParse);

  // Always recognise front matter, even in "ignore" mode - otherwise the `---`
  // fences parse as a thematic break followed by a setext heading, and the
  // metadata ends up printed as a title.
  processor.use(remarkFrontmatter, ["yaml"]);
  processor.use(remarkFrontMatter(frontMatterStore, markdown.frontMatter));

  if (markdown.gfm) processor.use(remarkGfm);
  if (markdown.softBreaks) processor.use(remarkBreaks);
  if (markdown.emoji) processor.use(remarkGemoji);
  if (markdown.math) processor.use(remarkMath);
  if (markdown.smartTypography) processor.use(remarkSmartypants);

  if (markdown.admonitions) {
    // remarkDirective is what turns `::: warning` into a containerDirective
    // node; remarkDirectiveCallouts only reshapes what it produces.
    processor.use(remarkDirective);
    processor.use(remarkGithubAlerts);
    processor.use(remarkDirectiveCallouts);
  }
  processor.use(remarkPageBreaks);

  processor.use(() => (tree: MdastRoot) => {
    wordCount = countWords(tree);
  });

  const allowRawHtml = markdown.rawHtml !== "strip";
  processor.use(remarkRehype, { allowDangerousHtml: allowRawHtml });
  if (allowRawHtml) processor.use(rehypeRaw);

  if (markdown.rawHtml !== "allow") {
    processor.use(rehypeSanitize, buildSanitizeSchema("sanitise"));
  }

  processor.use(rehypeSlug);
  processor.use(rehypeHeadings(headingStore, structure));

  if (markdown.math) processor.use(rehypeKatex);

  processor.use(rehypeHighlight, {
    detect: true,
    // Mermaid blocks are diagrams, not code. Highlighting them would wrap the
    // source in <span>s and make the diagram renderer's job impossible.
    plainText: ["mermaid", "text", "plain", "txt"],
  });

  processor.use(rehypeStringify, { allowDangerousHtml: markdown.rawHtml === "allow" });

  const html = String(
    processor.processSync(
      markdown.admonitions ? normaliseDirectiveSyntax(source) : source,
    ),
  );

  const frontMatterTitle = frontMatterStore.data.title;
  const title =
    typeof frontMatterTitle === "string" && frontMatterTitle.trim() !== ""
      ? frontMatterTitle.trim()
      : (headingStore.headings.find((heading) => heading.depth === 1)?.text ??
        null);

  return {
    html,
    headings: headingStore.headings,
    frontMatter: frontMatterStore.data,
    title,
    wordCount,
  };
}
