/**
 * Bakes third-party stylesheets into TypeScript modules.
 *
 * The document stylesheet is assembled as a *string* and handed to two places
 * that cannot resolve a bundler import or a CDN link: an <iframe> written with
 * srcdoc, and headless Chromium rendering detached HTML. So syntax-highlighting
 * themes and the KaTeX stylesheet have to be available as plain strings.
 *
 * Two outputs:
 *   src/lib/renderer/generated/code-themes.ts  - highlight.js themes, verbatim
 *   src/lib/renderer/generated/katex-css.ts    - KaTeX CSS, woff2-only, with
 *                                                absolute /katex/fonts URLs
 *   public/katex/fonts/*.woff2                 - the fonts that CSS points at
 *
 * Run: npm run styles (also runs automatically before dev and build)
 */
import { createRequire } from "node:module";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED_DIR = path.join(ROOT, "src", "lib", "renderer", "generated");
const KATEX_PUBLIC_DIR = path.join(ROOT, "public", "katex", "fonts");

/**
 * Kept in sync with CODE_THEMES in src/lib/config/schema.ts.
 * The test in code-themes.test.ts fails if the two drift apart.
 */
const CODE_THEMES = [
  "github",
  "atom-one-light",
  "a11y-light",
  "intellij-light",
  "xcode",
  "vs",
  "stackoverflow-light",
  "grayscale",
  "nnfx-light",
  "github-dark",
  "atom-one-dark",
];

const BANNER = "// GENERATED by scripts/sync-styles.mjs - do not edit by hand.";

function packageDir(pkg) {
  return path.dirname(require.resolve(`${pkg}/package.json`));
}

/** Serialise a string as a TS template literal, escaping what would break it. */
function asTemplateLiteral(value) {
  return `\`${value.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")}\``;
}

function buildCodeThemes() {
  const dir = path.join(packageDir("highlight.js"), "styles");
  const entries = [];

  for (const theme of CODE_THEMES) {
    const file = path.join(dir, `${theme}.min.css`);
    if (!fs.existsSync(file)) {
      throw new Error(`highlight.js has no theme "${theme}" (looked in ${dir})`);
    }
    const css = fs.readFileSync(file, "utf8").trim();
    entries.push(`  ${JSON.stringify(theme)}: ${asTemplateLiteral(css)},`);
  }

  const source = [
    BANNER,
    "",
    "/** highlight.js themes, keyed by the ids in CODE_THEMES. */",
    "export const CODE_THEME_CSS: Record<string, string> = {",
    ...entries,
    "};",
    "",
  ].join("\n");

  fs.writeFileSync(path.join(GENERATED_DIR, "code-themes.ts"), source);
  return CODE_THEMES.length;
}

function buildKatex() {
  const dir = packageDir("katex");
  const cssPath = path.join(dir, "dist", "katex.min.css");
  const fontsDir = path.join(dir, "dist", "fonts");

  fs.rmSync(KATEX_PUBLIC_DIR, { recursive: true, force: true });
  fs.mkdirSync(KATEX_PUBLIC_DIR, { recursive: true });

  let bytes = 0;
  let copied = 0;
  for (const file of fs.readdirSync(fontsDir)) {
    if (!file.endsWith(".woff2")) continue;
    const dest = path.join(KATEX_PUBLIC_DIR, file);
    fs.copyFileSync(path.join(fontsDir, file), dest);
    bytes += fs.statSync(dest).size;
    copied += 1;
  }

  // KaTeX ships each face as woff2 + woff + ttf. Everything that can run this
  // app supports woff2, so drop the other two: it removes ~900 KB of files we
  // would otherwise have to host, and shortens what Chromium has to inline.
  const original = fs.readFileSync(cssPath, "utf8");
  const rewritten = original.replace(
    /src\s*:\s*url\(\s*fonts\/([\w-]+)\.woff2\s*\)\s*format\(\s*["']woff2["']\s*\)[^;}]*/g,
    (_match, name) => `src:url(/katex/fonts/${name}.woff2) format("woff2")`,
  );

  const remaining = rewritten.match(/url\(\s*fonts\//g);
  if (remaining) {
    throw new Error(
      `KaTeX CSS still has ${remaining.length} unrewritten font URL(s) - the ` +
        "src rewrite regex no longer matches this version of katex.min.css.",
    );
  }

  const source = [
    BANNER,
    "",
    "/** KaTeX stylesheet, woff2 only, with absolute /katex/fonts URLs. */",
    `export const KATEX_CSS = ${asTemplateLiteral(rewritten.trim())};`,
    "",
    "/** Where the rewritten CSS expects the font files to be served from. */",
    'export const KATEX_FONT_BASE = "/katex/fonts/";',
    "",
  ].join("\n");

  fs.writeFileSync(path.join(GENERATED_DIR, "katex-css.ts"), source);
  return { copied, kb: Math.round(bytes / 1024) };
}

function main() {
  fs.mkdirSync(GENERATED_DIR, { recursive: true });

  const themeCount = buildCodeThemes();
  const katex = buildKatex();

  console.log(
    `styles: ${themeCount} code themes, KaTeX CSS + ${katex.copied} fonts (${katex.kb} KB)`,
  );
}

main();
